name: Python Unit Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: dlittleman/roman_baseline:v1.0.1
      options: --user root  # optional, helps avoid permission issue

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 
        run: |
          sudo ./install.sh
      - name: Run tests
        run: |
          python3 -m coverage run --source roman -m unittest discover tests/ -v
          python3 -m coverage report
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
